In [2]:
import numpy as np
import matplotlib.pyplot as plt
import math
import emcee

In [3]:
def gauss_elimination(A):
    n = A.shape[0]
    for i in range (n):
        for k in range (i+1,n):
            m = A[k,i]/A[i,i]
            A[k,: ] = A[k,: ] - m*A[i,: ]
    return A

In [5]:
A = np.array([[2, 1, -1, 1], [-3, -1, 2, 1], [-2, 1, 2, 1], [5, 2, 6, -5]],dtype=float)
print(A)
print(gauss_elimination(A))

[[ 2.  1. -1.  1.]
 [-3. -1.  2.  1.]
 [-2.  1.  2.  1.]
 [ 5.  2.  6. -5.]]
[[  2.    1.   -1.    1. ]
 [  0.    0.5   0.5   2.5]
 [  0.    0.   -1.   -8. ]
 [  0.    0.    0.  -77. ]]


In [4]:
A = np.array([[2, 1, -1, 1], [-3, -1, 2, 1], [-2, 1, 2, 1], [5, 2, 6, -5]],dtype=float)
b = np.array([[9],[-10],[-2],[5]], dtype = float)
B = np.hstack((A,b))
print(B)
print(gauss_elimination(B))

[[  2.   1.  -1.   1.   9.]
 [ -3.  -1.   2.   1. -10.]
 [ -2.   1.   2.   1.  -2.]
 [  5.   2.   6.  -5.   5.]]
[[  2.    1.   -1.    1.    9. ]
 [  0.    0.5   0.5   2.5   3.5]
 [  0.    0.   -1.   -8.   -7. ]
 [  0.    0.    0.  -77.  -77. ]]


In [5]:
def sol(A,b):
    n = A.shape[0]
    s = gauss_elimination(np.hstack((A,b)))
    solution = np.zeros((n,1)) 
    for i in range(n-1,-1,-1):
        solution[i] = s[i,n]
        for j in range(i+1,n):
            solution[i] = solution[i]-solution[j]*s[i,j]
        solution[i] = solution[i]/s[i,i]
    
    return solution    

In [6]:
A = np.array([[2, 1, -1, 1], [-3, -1, 2, 1], [-2, 1, 2, 1], [5, 2, 6, -5]],dtype=float)
b = np.array([[9],[-10],[-2],[5]], dtype = float)
print(sol(A,b))

[[ 2.]
 [ 3.]
 [-1.]
 [ 1.]]


# Gauss-Jordan elimination

In [7]:
def gauss_Jordan_elimination(A):
    n = A.shape[0]
    for i in range (n):
        for k in range (n):
            if i != k:
                A[k,: ] = A[k,: ] - A[i,: ]*A[k,i]/A[i,i]
    return A

In [8]:
A = np.array([[2, 1, -1, 1], [-3, -1, 2, 1], [-2, 1, 2, 1], [5, 2, 6, -5]],dtype=float)
print(gauss_Jordan_elimination(A))

[[  2.    0.    0.    0. ]
 [  0.    0.5   0.    0. ]
 [  0.    0.   -1.    0. ]
 [  0.    0.    0.  -77. ]]


In [9]:
A = np.array([[2, 1, -1, 1], [-3, -1, 2, 1], [-2, 1, 2, 1], [5, 2, 6, -5]],dtype=float)
b = np.array([[9],[-10],[-2],[5]])
B = np.hstack((A,b))
Z = gauss_Jordan_elimination(B)
print(Z)
Z = np.array([Z[i,:]/Z[i,i] for i in range(Z.shape[0])])
print (Z[:,4:])

[[  2.    0.    0.    0.    4. ]
 [  0.    0.5   0.    0.    1.5]
 [  0.    0.   -1.    0.    1. ]
 [  0.    0.    0.  -77.  -77. ]]
[[ 2.]
 [ 3.]
 [-1.]
 [ 1.]]


In [10]:
def gauss_Jordan_solution(A):
    n = A.shape[0]
    for i in range (n):
        A[i] = A[i]/A[i,i]
        for k in range (n):
            if i != k:
                A[k,: ] = A[k,: ] - A[i,: ]*A[k,i]
    return A

In [11]:
A = np.array([[2, 1, -1, 1], [-3, -1, 2, 1], [-2, 1, 2, 1], [5, 2, 6, -5]],dtype=float)
b = np.array([[9],[-10],[-2],[5]])
B = np.hstack((A,b))
print(gauss_Jordan_solution(B))
print(gauss_Jordan_solution(B)[:,4:])

[[ 1.  0.  0.  0.  2.]
 [ 0.  1.  0.  0.  3.]
 [ 0.  0.  1.  0. -1.]
 [-0. -0. -0.  1.  1.]]
[[ 2.]
 [ 3.]
 [-1.]
 [ 1.]]


In [12]:
def inverse(A):
    n = A.shape[0]
    I = np.eye(A.shape[0])
    A = np.hstack((A,I))
    for i in range (n):
        A[i] = A[i]/A[i,i]
        for k in range (n):
            if i != k:
                A[k,: ] = A[k,: ] - A[i,: ]*A[k,i]
    return A[:,A.shape[0]:]

In [13]:
A = np.array([[2, 1, -1, 1], [-3, -1, 2, 1], [-2, 1, 2, 1], [5, 2, 6, -5]],dtype=float)
inv = inverse(A)
np.set_printoptions(precision=2)
print(inv)

[[ 0.42  0.27 -0.3   0.08]
 [-0.21 -0.64  0.65 -0.04]
 [ 0.22  0.36 -0.06  0.1 ]
 [ 0.6   0.45 -0.12 -0.01]]


In [17]:
A = np.array([[2,1],
              [1,2]])
print(np.linalg.inv(A))
inv = inverse(A)
print(inv)


[[ 0.67 -0.33]
 [-0.33  0.67]]
[[ 0.67 -0.33]
 [-0.33  0.67]]
