In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

# 1. Kirchhoff’s circuit.

In [2]:
def gauss_elimination(A):
    n = A.shape[0]
    for i in range (n):
        for k in range (i+1,n):
            A[k] = A[k] - A[i]*A[k,i]/A[i,i]
    return A

In [3]:
r = np.array([[0, -10, 20],[10, 5, 0],[5, 15, -10]], dtype = float)
v = np.array([[5],[20],[10]], dtype = float)
print(f'resistance matrix =\n{r}')
print(f'Voltage vector =\n{v}')
x = np.hstack((r,v))
print(f'Combined =\n{x}')
a = np.array(x[0])
x[0] = np.array(x[1])
x[1] = a
print(f'Changed the rows =\n{x}')
s = gauss_elimination(x)
print(f'matrix after gauss elimination =\n{s}')

resistance matrix =
[[  0. -10.  20.]
 [ 10.   5.   0.]
 [  5.  15. -10.]]
Voltage vector =
[[ 5.]
 [20.]
 [10.]]
Combined =
[[  0. -10.  20.   5.]
 [ 10.   5.   0.  20.]
 [  5.  15. -10.  10.]]
Changed the rows =
[[ 10.   5.   0.  20.]
 [  0. -10.  20.   5.]
 [  5.  15. -10.  10.]]
matrix after gauss elimination =
[[ 10.     5.     0.    20.  ]
 [  0.   -10.    20.     5.  ]
 [  0.     0.    15.     6.25]]


In [4]:
def sol(x):
    n = x.shape[0]
    solution = np.zeros((n,1)) 
    for i in range(n-1,-1,-1):
        solution[i] = x[i,n]
        for j in range(i+1,n):
            solution[i] = solution[i]-solution[j]*x[i,j]
        solution[i] = solution[i]/x[i,i]
    
    return solution

In [5]:
I = sol(s)
a = np.array(I[0])
I[0] = np.array(I[1])
I[1] = a
print(f'The current vector is =\n{I}')
#print(I)
np.set_printoptions(precision=3)

The current vector is =
[[0.33333333]
 [1.83333333]
 [0.41666667]]


# 2. A rotating spacecraft

In [6]:
I = np.array([[2, -1, 3],[-2, 5, 1],[1, -3, 4]], dtype = float)
L = np.array([[3],[2],[1]], dtype = float)
print(f'Moment of inertia metrix =\n{I}')
print(f'Angular momentum vector =\n{L}')

Moment of inertia metrix =
[[ 2. -1.  3.]
 [-2.  5.  1.]
 [ 1. -3.  4.]]
Angular momentum vector =
[[3.]
 [2.]
 [1.]]


In [4]:
def inverse(A):
    n = A.shape[0]
    I = np.eye(A.shape[0])
    A = np.hstack((A,I))
    for i in range (n):
        A[i] = A[i]/A[i,i]
        for k in range (n):
            if i != k:
                A[k] = A[k] - A[i]*A[k,i]
    return A[:,A.shape[0]:]

In [8]:
# inverse of I
invI = inverse(I)
print(f'Inverse of moment of inertia metrix\n{invI}')
w = invI@L
print(f'The angular velocity vector =\n{w}')

Inverse of moment of inertia metrix
[[ 0.575 -0.125 -0.4  ]
 [ 0.225  0.125 -0.2  ]
 [ 0.025  0.125  0.2  ]]
The angular velocity vector =
[[1.075]
 [0.725]
 [0.525]]


# 3. Time Evolution Operator in Quantum Mechanics

In [7]:
t = 0.1
j = 1j
H = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
print(f'Hermitian metrix =\n{H}')
iHt = np.array((j*H*t), dtype = complex)
U = np.eye(H.shape[0]) - iHt
print(f'unitary matrix =\n{U}')
invU = inverse(U)
print(f'Inverse of unitary matrix =\n{invU}')
np.set_printoptions(precision=6, suppress=True)
I = invU@U
print(f'inverse(U)*U =\n{I}')


Hermitian metrix =
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
unitary matrix =
[[1.-0.2j 0.+0.1j 0.+0.j ]
 [0.+0.1j 1.-0.2j 0.+0.1j]
 [0.+0.j  0.+0.1j 1.-0.2j]]
Inverse of unitary matrix =
[[ 0.95+0.19j  0.04-0.09j -0.01-0.01j]
 [ 0.04-0.09j  0.95+0.18j  0.04-0.09j]
 [-0.01-0.01j  0.04-0.09j  0.95+0.19j]]
inverse(U)*U =
[[ 1.-0.j -0.-0.j  0.+0.j]
 [ 0.+0.j  1.+0.j -0.+0.j]
 [ 0.+0.j  0.+0.j  1.-0.j]]


# 4. Determinant of a square Matrix

In [2]:
def determinent(A):
    lemda,a = np.linalg.eig(A)
    #print(lemda)
    n = len(lemda)
    det = 1
    for i in range(n):
        det *= lemda[i]

    return det
        

In [4]:
import numpy as np

def get_determinant(matrix):
    # Base Case: If the matrix is 1x1, the determinant is the single element
    if len(matrix) == 1:
        return matrix[0, 0]

    # Base Case: If the matrix is 2x2, use the (ad - bc) formula
    if len(matrix) == 2:
        return (matrix[0, 0] * matrix[1, 1]) - (matrix[0, 1] * matrix[1, 0])

    determinant = 0
    
    # Loop through the first row to expand the determinant
    for c in range(len(matrix)):
        # 1. Create the Minor matrix (remove row 0 and current column 'c')
        minor = []
        for i in range(1, len(matrix)): # Start from row 1 to skip row 0
            row_data = []
            for j in range(len(matrix)):
                if j == c: 
                    continue # Skip the current column
                row_data.append(matrix[i, j])
            minor.append(row_data)
        
        minor_np = np.array(minor)

        # 2. Add to total: sign * element * determinant of smaller minor
        sign = (-1) ** c
        element = matrix[0, c]
        determinant += sign * element * get_determinant(minor_np)

    return determinant

# Example 3x3 Matrix
A = np.array([[1, 2, 3],
              [0, 4, 5],
              [1, 0, 6]],dtype = float)







result = get_determinant(A)

print("Matrix:\n", A)
print("\nCalculated Determinant:", result)


Matrix:
 [[1. 2. 3.]
 [0. 4. 5.]
 [1. 0. 6.]]

Calculated Determinant: 22.0


In [3]:
A = np.array([[1,2,3],[0,4,5],[1,0,6]],dtype = float)
print(determinent(A))

21.99999999999998


# Extra => Eigenvalue of 2*2 matrix

In [13]:
def eigenvalue(A):
    term1 = A[0,0]+A[1,1]
    term2 = A[0,0]*A[1,1] - A[0,1]*A[1,0]
    lemda = [0,0]
    lemda[1] = 0.5*(term1 + np.sqrt(term1**2 - 4*term2))
    lemda[0] = 0.5*(term1 - np.sqrt(term1**2 - 4*term2))
    return lemda

In [14]:
A = np.array([[1,1],[1,2]], dtype = float)
E = np.array(eigenvalue(A),dtype = float)
np.set_printoptions(precision=2, suppress=True)
print(f'calculated eigenvalues =\n{E}')
lemda,a = np.linalg.eig(A)
print(f'True eigenvalues =\n{lemda}')

calculated eigenvalues =
[0.38 2.62]
True eigenvalues =
[0.38 2.62]
